apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: chandanvura/shopflow-frontend:v1
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: API_GATEWAY_URL
          value: "http://api-gateway.shopflow.svc.cluster.local:80"